import {
  Activity,
  AlertTriangle,
  Archive,
  ArchiveRestore,
  ArrowDown,
  ArrowLeft,
  ArrowUp,
  BarChart3,
  BookOpen,
  Bot,
  Check,
  ChevronDown,
  ChevronRight,
  Code,
  Columns3,
  Copy,
  CopyMinus,
  Cpu,
  Download,
  ExternalLink,
  FileText,
  FilePlus2,
  FileCode2,
  FileJson,
  Image,
  FoldVertical,
  Folder,
  FolderGit2,
  FolderOpen,
  FolderPlus,
  GitCompare,
  GitMerge,
  GitPullRequest,
  Inbox,
  Info,
  Layers,
  List,
  ListTodo,
  ListTree,
  Loader,
  Mail,
  MailOpen,
  MessageSquare,
  Monitor,
  Moon,
  MoonStar,
  MoreHorizontal,
  Palette,
  Play,
  Plug,
  Plus,
  RefreshCw,
  Rows3,
  Rows4,
  Search,
  Settings,
  SlidersHorizontal,
  Square,
  Sun,
  Terminal,
  Timer,
  Trash2,
  UnfoldVertical,
  Wand2,
  Workflow,
  X,
  type LucideIcon,
} from "lucide-react";

export const icons = {
  activity: Activity,
  "alert-triangle": AlertTriangle,
  archive: Archive,
  "archive-restore": ArchiveRestore,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-up": ArrowUp,
  "bar-chart": BarChart3,
  book: BookOpen,
  bot: Bot,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  code: Code,
  "columns-3": Columns3,
  copy: Copy,
  "copy-minus": CopyMinus,
  cpu: Cpu,
  download: Download,
  "external-link": ExternalLink,
  "file-text": FileText,
  "file-plus": FilePlus2,
  "file-code": FileCode2,
  "file-json": FileJson,
  image: Image,
  "fold-vertical": FoldVertical,
  folder: Folder,
  "folder-git-2": FolderGit2,
  "folder-open": FolderOpen,
  "folder-plus": FolderPlus,
  "git-compare": GitCompare,
  "git-merge": GitMerge,
  "git-pull-request": GitPullRequest,
  inbox: Inbox,
  info: Info,
  layers: Layers,
  list: List,
  "list-todo": ListTodo,
  "list-tree": ListTree,
  loader: Loader,
  mail: Mail,
  "mail-open": MailOpen,
  "message-square": MessageSquare,
  monitor: Monitor,
  moon: Moon,
  "moon-star": MoonStar,
  "more-horizontal": MoreHorizontal,
  palette: Palette,
  play: Play,
  plug: Plug,
  plus: Plus,
  "refresh-cw": RefreshCw,
  "rows-3": Rows3,
  "rows-4": Rows4,
  search: Search,
  settings: Settings,
  "sliders-horizontal": SlidersHorizontal,
  square: Square,
  sun: Sun,
  terminal: Terminal,
  timer: Timer,
  "trash-2": Trash2,
  "unfold-vertical": UnfoldVertical,
  "wand-2": Wand2,
  workflow: Workflow,
  x: X,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;
