import {
  Activity,
  AlertTriangle,
  ArrowDown,
  ArrowUp,
  BarChart3,
  BookOpen,
  Bot,
  Check,
  ChevronDown,
  ChevronRight,
  Columns3,
  Cpu,
  FileText,
  Folder,
  FolderGit2,
  GitCompare,
  GitPullRequest,
  Inbox,
  Info,
  Layers,
  List,
  ListTodo,
  ListTree,
  Loader,
  MessageSquare,
  Monitor,
  Moon,
  MoonStar,
  MoreHorizontal,
  Palette,
  Play,
  Plug,
  Plus,
  RefreshCw,
  Rows3,
  Rows4,
  Search,
  Settings,
  SlidersHorizontal,
  Square,
  Sun,
  Terminal,
  UnfoldVertical,
  Wand2,
  Workflow,
  X,
  type LucideIcon,
} from "lucide-react";

export const icons = {
  activity: Activity,
  "alert-triangle": AlertTriangle,
  "arrow-down": ArrowDown,
  "arrow-up": ArrowUp,
  "bar-chart": BarChart3,
  book: BookOpen,
  bot: Bot,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "columns-3": Columns3,
  cpu: Cpu,
  "file-text": FileText,
  folder: Folder,
  "folder-git-2": FolderGit2,
  "git-compare": GitCompare,
  "git-pull-request": GitPullRequest,
  inbox: Inbox,
  info: Info,
  layers: Layers,
  list: List,
  "list-todo": ListTodo,
  "list-tree": ListTree,
  loader: Loader,
  "message-square": MessageSquare,
  monitor: Monitor,
  moon: Moon,
  "moon-star": MoonStar,
  "more-horizontal": MoreHorizontal,
  palette: Palette,
  play: Play,
  plug: Plug,
  plus: Plus,
  "refresh-cw": RefreshCw,
  "rows-3": Rows3,
  "rows-4": Rows4,
  search: Search,
  settings: Settings,
  "sliders-horizontal": SlidersHorizontal,
  square: Square,
  sun: Sun,
  terminal: Terminal,
  "unfold-vertical": UnfoldVertical,
  "wand-2": Wand2,
  workflow: Workflow,
  x: X,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;
