import {
  Activity,
  AlertTriangle,
  BarChart3,
  BookOpen,
  Bot,
  ChevronDown,
  Columns3,
  Cpu,
  Folder,
  FolderGit2,
  GitCompare,
  GitPullRequest,
  Inbox,
  Layers,
  List,
  ListTodo,
  ListTree,
  Loader,
  Monitor,
  Moon,
  MoonStar,
  MoreHorizontal,
  Palette,
  Play,
  Plus,
  Rows3,
  Rows4,
  Search,
  Settings,
  Square,
  Sun,
  Terminal,
  Wand2,
  type LucideIcon,
} from "lucide-react";

export const icons = {
  activity: Activity,
  "alert-triangle": AlertTriangle,
  "bar-chart": BarChart3,
  book: BookOpen,
  bot: Bot,
  "chevron-down": ChevronDown,
  "columns-3": Columns3,
  cpu: Cpu,
  folder: Folder,
  "folder-git-2": FolderGit2,
  "git-compare": GitCompare,
  "git-pull-request": GitPullRequest,
  inbox: Inbox,
  layers: Layers,
  list: List,
  "list-todo": ListTodo,
  "list-tree": ListTree,
  loader: Loader,
  monitor: Monitor,
  moon: Moon,
  "moon-star": MoonStar,
  "more-horizontal": MoreHorizontal,
  palette: Palette,
  play: Play,
  plus: Plus,
  "rows-3": Rows3,
  "rows-4": Rows4,
  search: Search,
  settings: Settings,
  square: Square,
  sun: Sun,
  terminal: Terminal,
  "wand-2": Wand2,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;
