/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as AgentsProfileIdRouteImport } from './routes/agents/$profileId'
import { Route as IssuesIndexRouteImport } from './routes/issues/index'
import { Route as IssuesIssueIdRouteImport } from './routes/issues/$issueId'
import { Route as RunsIndexRouteImport } from './routes/runs/index'
import { Route as RunsRunIdRouteRouteImport } from './routes/runs/$runId/route'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsAboutRouteImport } from './routes/settings/about'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsExecutionRouteImport } from './routes/settings/execution'
import { Route as SettingsHostRouteImport } from './routes/settings/host'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings/integrations'
import { Route as SettingsRepositoriesRouteImport } from './routes/settings/repositories'
import { Route as SettingsRuntimesRouteImport } from './routes/settings/runtimes'
import { Route as SettingsSandboxRouteImport } from './routes/settings/sandbox'
import { Route as SettingsSkillsRouteImport } from './routes/settings/skills'
import { Route as SettingsWorkflowPresetsRouteImport } from './routes/settings/workflow-presets'
import { Route as SettingsWorkspacesRouteImport } from './routes/settings/workspaces'
import { Route as PullRequestsPullRequestIdDiffRouteImport } from './routes/pull-requests/$pullRequestId/diff'
import { Route as RunsRunIdIndexRouteImport } from './routes/runs/$runId/index'
import { Route as RunsRunIdDiffRouteImport } from './routes/runs/$runId/diff'
import { Route as RunsRunIdLogsRouteImport } from './routes/runs/$runId/logs'
import { Route as RunsRunIdPrRouteImport } from './routes/runs/$runId/pr'
import { Route as RunsRunIdReportRouteImport } from './routes/runs/$runId/report'
import { Route as SettingsAgentsIndexRouteImport } from './routes/settings/agents/index'
import { Route as SettingsAgentsProfileIdRouteImport } from './routes/settings/agents/$profileId'
import { Route as SettingsProjectIndexRouteImport } from './routes/settings/project/index'
import { Route as SettingsProjectAgentsRouteImport } from './routes/settings/project/agents'
import { Route as SettingsProjectSkillsRouteImport } from './routes/settings/project/skills'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsRoute,
} as any)
const AgentsProfileIdRoute = AgentsProfileIdRouteImport.update({
  id: '/$profileId',
  path: '/$profileId',
  getParentRoute: () => AgentsRoute,
} as any)
const IssuesIndexRoute = IssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIssueIdRoute = IssuesIssueIdRouteImport.update({
  id: '/issues/$issueId',
  path: '/issues/$issueId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRouteRoute = RunsRunIdRouteRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsExecutionRoute = SettingsExecutionRouteImport.update({
  id: '/execution',
  path: '/execution',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsHostRoute = SettingsHostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsRepositoriesRoute = SettingsRepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsRuntimesRoute = SettingsRuntimesRouteImport.update({
  id: '/runtimes',
  path: '/runtimes',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsSandboxRoute = SettingsSandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsSkillsRoute = SettingsSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsWorkflowPresetsRoute = SettingsWorkflowPresetsRouteImport.update({
  id: '/workflow-presets',
  path: '/workflow-presets',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsWorkspacesRoute = SettingsWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const PullRequestsPullRequestIdDiffRoute =
  PullRequestsPullRequestIdDiffRouteImport.update({
    id: '/pull-requests/$pullRequestId/diff',
    path: '/pull-requests/$pullRequestId/diff',
    getParentRoute: () => rootRouteImport,
  } as any)
const RunsRunIdIndexRoute = RunsRunIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RunsRunIdRouteRoute,
} as any)
const RunsRunIdDiffRoute = RunsRunIdDiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => RunsRunIdRouteRoute,
} as any)
const RunsRunIdLogsRoute = RunsRunIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => RunsRunIdRouteRoute,
} as any)
const RunsRunIdPrRoute = RunsRunIdPrRouteImport.update({
  id: '/pr',
  path: '/pr',
  getParentRoute: () => RunsRunIdRouteRoute,
} as any)
const RunsRunIdReportRoute = RunsRunIdReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => RunsRunIdRouteRoute,
} as any)
const SettingsAgentsIndexRoute = SettingsAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAgentsProfileIdRoute = SettingsAgentsProfileIdRouteImport.update({
  id: '/agents/$profileId',
  path: '/agents/$profileId',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsProjectIndexRoute = SettingsProjectIndexRouteImport.update({
  id: '/project/',
  path: '/project/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsProjectAgentsRoute = SettingsProjectAgentsRouteImport.update({
  id: '/project/agents',
  path: '/project/agents',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsProjectSkillsRoute = SettingsProjectSkillsRouteImport.update({
  id: '/project/skills',
  path: '/project/skills',
  getParentRoute: () => SettingsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/agents': typeof AgentsRouteWithChildren
  '/inbox': typeof InboxRoute
  '/reviews': typeof ReviewsRoute
  '/skills': typeof SkillsRoute
  '/usage': typeof UsageRoute
  '/runs/$runId': typeof RunsRunIdRouteRouteWithChildren
  '/agents/$profileId': typeof AgentsProfileIdRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/execution': typeof SettingsExecutionRoute
  '/settings/host': typeof SettingsHostRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/repositories': typeof SettingsRepositoriesRoute
  '/settings/runtimes': typeof SettingsRuntimesRoute
  '/settings/sandbox': typeof SettingsSandboxRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/settings/workflow-presets': typeof SettingsWorkflowPresetsRoute
  '/settings/workspaces': typeof SettingsWorkspacesRoute
  '/agents/': typeof AgentsIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/pull-requests/$pullRequestId/diff': typeof PullRequestsPullRequestIdDiffRoute
  '/runs/$runId/diff': typeof RunsRunIdDiffRoute
  '/runs/$runId/logs': typeof RunsRunIdLogsRoute
  '/runs/$runId/pr': typeof RunsRunIdPrRoute
  '/runs/$runId/report': typeof RunsRunIdReportRoute
  '/settings/agents/$profileId': typeof SettingsAgentsProfileIdRoute
  '/settings/project/agents': typeof SettingsProjectAgentsRoute
  '/settings/project/skills': typeof SettingsProjectSkillsRoute
  '/runs/$runId/': typeof RunsRunIdIndexRoute
  '/settings/agents/': typeof SettingsAgentsIndexRoute
  '/settings/project/': typeof SettingsProjectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inbox': typeof InboxRoute
  '/reviews': typeof ReviewsRoute
  '/skills': typeof SkillsRoute
  '/usage': typeof UsageRoute
  '/agents/$profileId': typeof AgentsProfileIdRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/execution': typeof SettingsExecutionRoute
  '/settings/host': typeof SettingsHostRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/repositories': typeof SettingsRepositoriesRoute
  '/settings/runtimes': typeof SettingsRuntimesRoute
  '/settings/sandbox': typeof SettingsSandboxRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/settings/workflow-presets': typeof SettingsWorkflowPresetsRoute
  '/settings/workspaces': typeof SettingsWorkspacesRoute
  '/agents': typeof AgentsIndexRoute
  '/issues': typeof IssuesIndexRoute
  '/runs': typeof RunsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/pull-requests/$pullRequestId/diff': typeof PullRequestsPullRequestIdDiffRoute
  '/runs/$runId/diff': typeof RunsRunIdDiffRoute
  '/runs/$runId/logs': typeof RunsRunIdLogsRoute
  '/runs/$runId/pr': typeof RunsRunIdPrRoute
  '/runs/$runId/report': typeof RunsRunIdReportRoute
  '/settings/agents/$profileId': typeof SettingsAgentsProfileIdRoute
  '/settings/project/agents': typeof SettingsProjectAgentsRoute
  '/settings/project/skills': typeof SettingsProjectSkillsRoute
  '/runs/$runId': typeof RunsRunIdIndexRoute
  '/settings/agents': typeof SettingsAgentsIndexRoute
  '/settings/project': typeof SettingsProjectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/agents': typeof AgentsRouteWithChildren
  '/inbox': typeof InboxRoute
  '/reviews': typeof ReviewsRoute
  '/skills': typeof SkillsRoute
  '/usage': typeof UsageRoute
  '/runs/$runId': typeof RunsRunIdRouteRouteWithChildren
  '/agents/$profileId': typeof AgentsProfileIdRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/execution': typeof SettingsExecutionRoute
  '/settings/host': typeof SettingsHostRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/repositories': typeof SettingsRepositoriesRoute
  '/settings/runtimes': typeof SettingsRuntimesRoute
  '/settings/sandbox': typeof SettingsSandboxRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/settings/workflow-presets': typeof SettingsWorkflowPresetsRoute
  '/settings/workspaces': typeof SettingsWorkspacesRoute
  '/agents/': typeof AgentsIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/pull-requests/$pullRequestId/diff': typeof PullRequestsPullRequestIdDiffRoute
  '/runs/$runId/diff': typeof RunsRunIdDiffRoute
  '/runs/$runId/logs': typeof RunsRunIdLogsRoute
  '/runs/$runId/pr': typeof RunsRunIdPrRoute
  '/runs/$runId/report': typeof RunsRunIdReportRoute
  '/settings/agents/$profileId': typeof SettingsAgentsProfileIdRoute
  '/settings/project/agents': typeof SettingsProjectAgentsRoute
  '/settings/project/skills': typeof SettingsProjectSkillsRoute
  '/runs/$runId/': typeof RunsRunIdIndexRoute
  '/settings/agents/': typeof SettingsAgentsIndexRoute
  '/settings/project/': typeof SettingsProjectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/agents'
    | '/inbox'
    | '/reviews'
    | '/skills'
    | '/usage'
    | '/runs/$runId'
    | '/agents/$profileId'
    | '/issues/$issueId'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/execution'
    | '/settings/host'
    | '/settings/integrations'
    | '/settings/repositories'
    | '/settings/runtimes'
    | '/settings/sandbox'
    | '/settings/skills'
    | '/settings/workflow-presets'
    | '/settings/workspaces'
    | '/agents/'
    | '/issues/'
    | '/runs/'
    | '/settings/'
    | '/pull-requests/$pullRequestId/diff'
    | '/runs/$runId/diff'
    | '/runs/$runId/logs'
    | '/runs/$runId/pr'
    | '/runs/$runId/report'
    | '/settings/agents/$profileId'
    | '/settings/project/agents'
    | '/settings/project/skills'
    | '/runs/$runId/'
    | '/settings/agents/'
    | '/settings/project/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inbox'
    | '/reviews'
    | '/skills'
    | '/usage'
    | '/agents/$profileId'
    | '/issues/$issueId'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/execution'
    | '/settings/host'
    | '/settings/integrations'
    | '/settings/repositories'
    | '/settings/runtimes'
    | '/settings/sandbox'
    | '/settings/skills'
    | '/settings/workflow-presets'
    | '/settings/workspaces'
    | '/agents'
    | '/issues'
    | '/runs'
    | '/settings'
    | '/pull-requests/$pullRequestId/diff'
    | '/runs/$runId/diff'
    | '/runs/$runId/logs'
    | '/runs/$runId/pr'
    | '/runs/$runId/report'
    | '/settings/agents/$profileId'
    | '/settings/project/agents'
    | '/settings/project/skills'
    | '/runs/$runId'
    | '/settings/agents'
    | '/settings/project'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/agents'
    | '/inbox'
    | '/reviews'
    | '/skills'
    | '/usage'
    | '/runs/$runId'
    | '/agents/$profileId'
    | '/issues/$issueId'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/execution'
    | '/settings/host'
    | '/settings/integrations'
    | '/settings/repositories'
    | '/settings/runtimes'
    | '/settings/sandbox'
    | '/settings/skills'
    | '/settings/workflow-presets'
    | '/settings/workspaces'
    | '/agents/'
    | '/issues/'
    | '/runs/'
    | '/settings/'
    | '/pull-requests/$pullRequestId/diff'
    | '/runs/$runId/diff'
    | '/runs/$runId/logs'
    | '/runs/$runId/pr'
    | '/runs/$runId/report'
    | '/settings/agents/$profileId'
    | '/settings/project/agents'
    | '/settings/project/skills'
    | '/runs/$runId/'
    | '/settings/agents/'
    | '/settings/project/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  AgentsRoute: typeof AgentsRouteWithChildren
  InboxRoute: typeof InboxRoute
  ReviewsRoute: typeof ReviewsRoute
  SkillsRoute: typeof SkillsRoute
  UsageRoute: typeof UsageRoute
  RunsRunIdRouteRoute: typeof RunsRunIdRouteRouteWithChildren
  IssuesIssueIdRoute: typeof IssuesIssueIdRoute
  IssuesIndexRoute: typeof IssuesIndexRoute
  RunsIndexRoute: typeof RunsIndexRoute
  PullRequestsPullRequestIdDiffRoute: typeof PullRequestsPullRequestIdDiffRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agents/$profileId': {
      id: '/agents/$profileId'
      path: '/$profileId'
      fullPath: '/agents/$profileId'
      preLoaderRoute: typeof AgentsProfileIdRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/issues/': {
      id: '/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof IssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$issueId': {
      id: '/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/issues/$issueId'
      preLoaderRoute: typeof IssuesIssueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/execution': {
      id: '/settings/execution'
      path: '/execution'
      fullPath: '/settings/execution'
      preLoaderRoute: typeof SettingsExecutionRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/host': {
      id: '/settings/host'
      path: '/host'
      fullPath: '/settings/host'
      preLoaderRoute: typeof SettingsHostRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/repositories': {
      id: '/settings/repositories'
      path: '/repositories'
      fullPath: '/settings/repositories'
      preLoaderRoute: typeof SettingsRepositoriesRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/runtimes': {
      id: '/settings/runtimes'
      path: '/runtimes'
      fullPath: '/settings/runtimes'
      preLoaderRoute: typeof SettingsRuntimesRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/sandbox': {
      id: '/settings/sandbox'
      path: '/sandbox'
      fullPath: '/settings/sandbox'
      preLoaderRoute: typeof SettingsSandboxRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/skills': {
      id: '/settings/skills'
      path: '/skills'
      fullPath: '/settings/skills'
      preLoaderRoute: typeof SettingsSkillsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/workflow-presets': {
      id: '/settings/workflow-presets'
      path: '/workflow-presets'
      fullPath: '/settings/workflow-presets'
      preLoaderRoute: typeof SettingsWorkflowPresetsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/workspaces': {
      id: '/settings/workspaces'
      path: '/workspaces'
      fullPath: '/settings/workspaces'
      preLoaderRoute: typeof SettingsWorkspacesRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/pull-requests/$pullRequestId/diff': {
      id: '/pull-requests/$pullRequestId/diff'
      path: '/pull-requests/$pullRequestId/diff'
      fullPath: '/pull-requests/$pullRequestId/diff'
      preLoaderRoute: typeof PullRequestsPullRequestIdDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId/': {
      id: '/runs/$runId/'
      path: '/'
      fullPath: '/runs/$runId/'
      preLoaderRoute: typeof RunsRunIdIndexRouteImport
      parentRoute: typeof RunsRunIdRouteRoute
    }
    '/runs/$runId/diff': {
      id: '/runs/$runId/diff'
      path: '/diff'
      fullPath: '/runs/$runId/diff'
      preLoaderRoute: typeof RunsRunIdDiffRouteImport
      parentRoute: typeof RunsRunIdRouteRoute
    }
    '/runs/$runId/logs': {
      id: '/runs/$runId/logs'
      path: '/logs'
      fullPath: '/runs/$runId/logs'
      preLoaderRoute: typeof RunsRunIdLogsRouteImport
      parentRoute: typeof RunsRunIdRouteRoute
    }
    '/runs/$runId/pr': {
      id: '/runs/$runId/pr'
      path: '/pr'
      fullPath: '/runs/$runId/pr'
      preLoaderRoute: typeof RunsRunIdPrRouteImport
      parentRoute: typeof RunsRunIdRouteRoute
    }
    '/runs/$runId/report': {
      id: '/runs/$runId/report'
      path: '/report'
      fullPath: '/runs/$runId/report'
      preLoaderRoute: typeof RunsRunIdReportRouteImport
      parentRoute: typeof RunsRunIdRouteRoute
    }
    '/settings/agents/': {
      id: '/settings/agents/'
      path: '/agents'
      fullPath: '/settings/agents/'
      preLoaderRoute: typeof SettingsAgentsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/agents/$profileId': {
      id: '/settings/agents/$profileId'
      path: '/agents/$profileId'
      fullPath: '/settings/agents/$profileId'
      preLoaderRoute: typeof SettingsAgentsProfileIdRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/project/': {
      id: '/settings/project/'
      path: '/project'
      fullPath: '/settings/project/'
      preLoaderRoute: typeof SettingsProjectIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/project/agents': {
      id: '/settings/project/agents'
      path: '/project/agents'
      fullPath: '/settings/project/agents'
      preLoaderRoute: typeof SettingsProjectAgentsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/project/skills': {
      id: '/settings/project/skills'
      path: '/project/skills'
      fullPath: '/settings/project/skills'
      preLoaderRoute: typeof SettingsProjectSkillsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsExecutionRoute: typeof SettingsExecutionRoute
  SettingsHostRoute: typeof SettingsHostRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsRepositoriesRoute: typeof SettingsRepositoriesRoute
  SettingsRuntimesRoute: typeof SettingsRuntimesRoute
  SettingsSandboxRoute: typeof SettingsSandboxRoute
  SettingsSkillsRoute: typeof SettingsSkillsRoute
  SettingsWorkflowPresetsRoute: typeof SettingsWorkflowPresetsRoute
  SettingsWorkspacesRoute: typeof SettingsWorkspacesRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsAgentsProfileIdRoute: typeof SettingsAgentsProfileIdRoute
  SettingsProjectAgentsRoute: typeof SettingsProjectAgentsRoute
  SettingsProjectSkillsRoute: typeof SettingsProjectSkillsRoute
  SettingsAgentsIndexRoute: typeof SettingsAgentsIndexRoute
  SettingsProjectIndexRoute: typeof SettingsProjectIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsExecutionRoute: SettingsExecutionRoute,
  SettingsHostRoute: SettingsHostRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsRepositoriesRoute: SettingsRepositoriesRoute,
  SettingsRuntimesRoute: SettingsRuntimesRoute,
  SettingsSandboxRoute: SettingsSandboxRoute,
  SettingsSkillsRoute: SettingsSkillsRoute,
  SettingsWorkflowPresetsRoute: SettingsWorkflowPresetsRoute,
  SettingsWorkspacesRoute: SettingsWorkspacesRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsAgentsProfileIdRoute: SettingsAgentsProfileIdRoute,
  SettingsProjectAgentsRoute: SettingsProjectAgentsRoute,
  SettingsProjectSkillsRoute: SettingsProjectSkillsRoute,
  SettingsAgentsIndexRoute: SettingsAgentsIndexRoute,
  SettingsProjectIndexRoute: SettingsProjectIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface AgentsRouteChildren {
  AgentsProfileIdRoute: typeof AgentsProfileIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsProfileIdRoute: AgentsProfileIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface RunsRunIdRouteRouteChildren {
  RunsRunIdDiffRoute: typeof RunsRunIdDiffRoute
  RunsRunIdLogsRoute: typeof RunsRunIdLogsRoute
  RunsRunIdPrRoute: typeof RunsRunIdPrRoute
  RunsRunIdReportRoute: typeof RunsRunIdReportRoute
  RunsRunIdIndexRoute: typeof RunsRunIdIndexRoute
}

const RunsRunIdRouteRouteChildren: RunsRunIdRouteRouteChildren = {
  RunsRunIdDiffRoute: RunsRunIdDiffRoute,
  RunsRunIdLogsRoute: RunsRunIdLogsRoute,
  RunsRunIdPrRoute: RunsRunIdPrRoute,
  RunsRunIdReportRoute: RunsRunIdReportRoute,
  RunsRunIdIndexRoute: RunsRunIdIndexRoute,
}

const RunsRunIdRouteRouteWithChildren = RunsRunIdRouteRoute._addFileChildren(
  RunsRunIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  AgentsRoute: AgentsRouteWithChildren,
  InboxRoute: InboxRoute,
  ReviewsRoute: ReviewsRoute,
  SkillsRoute: SkillsRoute,
  UsageRoute: UsageRoute,
  RunsRunIdRouteRoute: RunsRunIdRouteRouteWithChildren,
  IssuesIssueIdRoute: IssuesIssueIdRoute,
  IssuesIndexRoute: IssuesIndexRoute,
  RunsIndexRoute: RunsIndexRoute,
  PullRequestsPullRequestIdDiffRoute: PullRequestsPullRequestIdDiffRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
