/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as AgentsProfileIdRouteImport } from './routes/agents/$profileId'
import { Route as IssuesIndexRouteImport } from './routes/issues/index'
import { Route as IssuesIssueIdRouteImport } from './routes/issues/$issueId'
import { Route as RunsIndexRouteImport } from './routes/runs/index'
import { Route as RunsRunIdRouteRouteImport } from './routes/runs/$runId/route'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsAboutRouteImport } from './routes/settings/about'
import { Route as SettingsAgentsRouteImport } from './routes/settings/agents'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings/integrations'
import { Route as SettingsRepositoriesRouteImport } from './routes/settings/repositories'
import { Route as SettingsRuntimesRouteImport } from './routes/settings/runtimes'
import { Route as RunsRunIdIndexRouteImport } from './routes/runs/$runId/index'
import { Route as RunsRunIdDiffRouteImport } from './routes/runs/$runId/diff'
import { Route as RunsRunIdLogsRouteImport } from './routes/runs/$runId/logs'
import { Route as RunsRunIdPrRouteImport } from './routes/runs/$runId/pr'
import { Route as RunsRunIdReportRouteImport } from './routes/runs/$runId/report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsRoute,
} as any)
const AgentsProfileIdRoute = AgentsProfileIdRouteImport.update({
  id: '/$profileId',
  path: '/$profileId',
  getParentRoute: () => AgentsRoute,
} as any)
const IssuesIndexRoute = IssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIssueIdRoute = IssuesIssueIdRouteImport.update({
  id: '/issues/$issueId',
  path: '/issues/$issueId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRouteRoute = RunsRunIdRouteRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAgentsRoute = SettingsAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsRepositoriesRoute = SettingsRepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsRuntimesRoute = SettingsRuntimesRouteImport.update({
  id: '/runtimes',
  path: '/runtimes',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const RunsRunIdIndexRoute = RunsRunIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RunsRunIdRouteRoute,
} as any)
const RunsRunIdDiffRoute = RunsRunIdDiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => RunsRunIdRouteRoute,
} as any)
const RunsRunIdLogsRoute = RunsRunIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => RunsRunIdRouteRoute,
} as any)
const RunsRunIdPrRoute = RunsRunIdPrRouteImport.update({
  id: '/pr',
  path: '/pr',
  getParentRoute: () => RunsRunIdRouteRoute,
} as any)
const RunsRunIdReportRoute = RunsRunIdReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => RunsRunIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/agents': typeof AgentsRouteWithChildren
  '/inbox': typeof InboxRoute
  '/reviews': typeof ReviewsRoute
  '/skills': typeof SkillsRoute
  '/usage': typeof UsageRoute
  '/runs/$runId': typeof RunsRunIdRouteRouteWithChildren
  '/agents/$profileId': typeof AgentsProfileIdRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/repositories': typeof SettingsRepositoriesRoute
  '/settings/runtimes': typeof SettingsRuntimesRoute
  '/agents/': typeof AgentsIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/runs/$runId/diff': typeof RunsRunIdDiffRoute
  '/runs/$runId/logs': typeof RunsRunIdLogsRoute
  '/runs/$runId/pr': typeof RunsRunIdPrRoute
  '/runs/$runId/report': typeof RunsRunIdReportRoute
  '/runs/$runId/': typeof RunsRunIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inbox': typeof InboxRoute
  '/reviews': typeof ReviewsRoute
  '/skills': typeof SkillsRoute
  '/usage': typeof UsageRoute
  '/agents/$profileId': typeof AgentsProfileIdRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/repositories': typeof SettingsRepositoriesRoute
  '/settings/runtimes': typeof SettingsRuntimesRoute
  '/agents': typeof AgentsIndexRoute
  '/issues': typeof IssuesIndexRoute
  '/runs': typeof RunsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/runs/$runId/diff': typeof RunsRunIdDiffRoute
  '/runs/$runId/logs': typeof RunsRunIdLogsRoute
  '/runs/$runId/pr': typeof RunsRunIdPrRoute
  '/runs/$runId/report': typeof RunsRunIdReportRoute
  '/runs/$runId': typeof RunsRunIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/agents': typeof AgentsRouteWithChildren
  '/inbox': typeof InboxRoute
  '/reviews': typeof ReviewsRoute
  '/skills': typeof SkillsRoute
  '/usage': typeof UsageRoute
  '/runs/$runId': typeof RunsRunIdRouteRouteWithChildren
  '/agents/$profileId': typeof AgentsProfileIdRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/repositories': typeof SettingsRepositoriesRoute
  '/settings/runtimes': typeof SettingsRuntimesRoute
  '/agents/': typeof AgentsIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/runs/$runId/diff': typeof RunsRunIdDiffRoute
  '/runs/$runId/logs': typeof RunsRunIdLogsRoute
  '/runs/$runId/pr': typeof RunsRunIdPrRoute
  '/runs/$runId/report': typeof RunsRunIdReportRoute
  '/runs/$runId/': typeof RunsRunIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/agents'
    | '/inbox'
    | '/reviews'
    | '/skills'
    | '/usage'
    | '/runs/$runId'
    | '/agents/$profileId'
    | '/issues/$issueId'
    | '/settings/about'
    | '/settings/agents'
    | '/settings/appearance'
    | '/settings/integrations'
    | '/settings/repositories'
    | '/settings/runtimes'
    | '/agents/'
    | '/issues/'
    | '/runs/'
    | '/settings/'
    | '/runs/$runId/diff'
    | '/runs/$runId/logs'
    | '/runs/$runId/pr'
    | '/runs/$runId/report'
    | '/runs/$runId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inbox'
    | '/reviews'
    | '/skills'
    | '/usage'
    | '/agents/$profileId'
    | '/issues/$issueId'
    | '/settings/about'
    | '/settings/agents'
    | '/settings/appearance'
    | '/settings/integrations'
    | '/settings/repositories'
    | '/settings/runtimes'
    | '/agents'
    | '/issues'
    | '/runs'
    | '/settings'
    | '/runs/$runId/diff'
    | '/runs/$runId/logs'
    | '/runs/$runId/pr'
    | '/runs/$runId/report'
    | '/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/agents'
    | '/inbox'
    | '/reviews'
    | '/skills'
    | '/usage'
    | '/runs/$runId'
    | '/agents/$profileId'
    | '/issues/$issueId'
    | '/settings/about'
    | '/settings/agents'
    | '/settings/appearance'
    | '/settings/integrations'
    | '/settings/repositories'
    | '/settings/runtimes'
    | '/agents/'
    | '/issues/'
    | '/runs/'
    | '/settings/'
    | '/runs/$runId/diff'
    | '/runs/$runId/logs'
    | '/runs/$runId/pr'
    | '/runs/$runId/report'
    | '/runs/$runId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  AgentsRoute: typeof AgentsRouteWithChildren
  InboxRoute: typeof InboxRoute
  ReviewsRoute: typeof ReviewsRoute
  SkillsRoute: typeof SkillsRoute
  UsageRoute: typeof UsageRoute
  RunsRunIdRouteRoute: typeof RunsRunIdRouteRouteWithChildren
  IssuesIssueIdRoute: typeof IssuesIssueIdRoute
  IssuesIndexRoute: typeof IssuesIndexRoute
  RunsIndexRoute: typeof RunsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agents/$profileId': {
      id: '/agents/$profileId'
      path: '/$profileId'
      fullPath: '/agents/$profileId'
      preLoaderRoute: typeof AgentsProfileIdRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/issues/': {
      id: '/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof IssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$issueId': {
      id: '/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/issues/$issueId'
      preLoaderRoute: typeof IssuesIssueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/agents': {
      id: '/settings/agents'
      path: '/agents'
      fullPath: '/settings/agents'
      preLoaderRoute: typeof SettingsAgentsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/repositories': {
      id: '/settings/repositories'
      path: '/repositories'
      fullPath: '/settings/repositories'
      preLoaderRoute: typeof SettingsRepositoriesRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/runtimes': {
      id: '/settings/runtimes'
      path: '/runtimes'
      fullPath: '/settings/runtimes'
      preLoaderRoute: typeof SettingsRuntimesRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/runs/$runId/': {
      id: '/runs/$runId/'
      path: '/'
      fullPath: '/runs/$runId/'
      preLoaderRoute: typeof RunsRunIdIndexRouteImport
      parentRoute: typeof RunsRunIdRouteRoute
    }
    '/runs/$runId/diff': {
      id: '/runs/$runId/diff'
      path: '/diff'
      fullPath: '/runs/$runId/diff'
      preLoaderRoute: typeof RunsRunIdDiffRouteImport
      parentRoute: typeof RunsRunIdRouteRoute
    }
    '/runs/$runId/logs': {
      id: '/runs/$runId/logs'
      path: '/logs'
      fullPath: '/runs/$runId/logs'
      preLoaderRoute: typeof RunsRunIdLogsRouteImport
      parentRoute: typeof RunsRunIdRouteRoute
    }
    '/runs/$runId/pr': {
      id: '/runs/$runId/pr'
      path: '/pr'
      fullPath: '/runs/$runId/pr'
      preLoaderRoute: typeof RunsRunIdPrRouteImport
      parentRoute: typeof RunsRunIdRouteRoute
    }
    '/runs/$runId/report': {
      id: '/runs/$runId/report'
      path: '/report'
      fullPath: '/runs/$runId/report'
      preLoaderRoute: typeof RunsRunIdReportRouteImport
      parentRoute: typeof RunsRunIdRouteRoute
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsAgentsRoute: typeof SettingsAgentsRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsRepositoriesRoute: typeof SettingsRepositoriesRoute
  SettingsRuntimesRoute: typeof SettingsRuntimesRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAgentsRoute: SettingsAgentsRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsRepositoriesRoute: SettingsRepositoriesRoute,
  SettingsRuntimesRoute: SettingsRuntimesRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface AgentsRouteChildren {
  AgentsProfileIdRoute: typeof AgentsProfileIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsProfileIdRoute: AgentsProfileIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface RunsRunIdRouteRouteChildren {
  RunsRunIdDiffRoute: typeof RunsRunIdDiffRoute
  RunsRunIdLogsRoute: typeof RunsRunIdLogsRoute
  RunsRunIdPrRoute: typeof RunsRunIdPrRoute
  RunsRunIdReportRoute: typeof RunsRunIdReportRoute
  RunsRunIdIndexRoute: typeof RunsRunIdIndexRoute
}

const RunsRunIdRouteRouteChildren: RunsRunIdRouteRouteChildren = {
  RunsRunIdDiffRoute: RunsRunIdDiffRoute,
  RunsRunIdLogsRoute: RunsRunIdLogsRoute,
  RunsRunIdPrRoute: RunsRunIdPrRoute,
  RunsRunIdReportRoute: RunsRunIdReportRoute,
  RunsRunIdIndexRoute: RunsRunIdIndexRoute,
}

const RunsRunIdRouteRouteWithChildren = RunsRunIdRouteRoute._addFileChildren(
  RunsRunIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  AgentsRoute: AgentsRouteWithChildren,
  InboxRoute: InboxRoute,
  ReviewsRoute: ReviewsRoute,
  SkillsRoute: SkillsRoute,
  UsageRoute: UsageRoute,
  RunsRunIdRouteRoute: RunsRunIdRouteRouteWithChildren,
  IssuesIssueIdRoute: IssuesIssueIdRoute,
  IssuesIndexRoute: IssuesIndexRoute,
  RunsIndexRoute: RunsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
