/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as IssuesIndexRouteImport } from './routes/issues/index'
import { Route as SettingsRuntimesRouteImport } from './routes/settings/runtimes'
import { Route as SettingsRepositoriesRouteImport } from './routes/settings/repositories'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsAgentsRouteImport } from './routes/settings/agents'
import { Route as SettingsAboutRouteImport } from './routes/settings/about'
import { Route as IssuesIssueIdRouteImport } from './routes/issues/$issueId'
import { Route as RunsRunIdRouteRouteImport } from './routes/runs/$runId/route'
import { Route as RunsRunIdIndexRouteImport } from './routes/runs/$runId/index'
import { Route as RunsRunIdDiffRouteImport } from './routes/runs/$runId/diff'

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const IssuesIndexRoute = IssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRuntimesRoute = SettingsRuntimesRouteImport.update({
  id: '/runtimes',
  path: '/runtimes',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsRepositoriesRoute = SettingsRepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAgentsRoute = SettingsAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const IssuesIssueIdRoute = IssuesIssueIdRouteImport.update({
  id: '/issues/$issueId',
  path: '/issues/$issueId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRouteRoute = RunsRunIdRouteRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdIndexRoute = RunsRunIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RunsRunIdRouteRoute,
} as any)
const RunsRunIdDiffRoute = RunsRunIdDiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => RunsRunIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/runs/$runId': typeof RunsRunIdRouteRouteWithChildren
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/repositories': typeof SettingsRepositoriesRoute
  '/settings/runtimes': typeof SettingsRuntimesRoute
  '/issues/': typeof IssuesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/runs/$runId/diff': typeof RunsRunIdDiffRoute
  '/runs/$runId/': typeof RunsRunIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/repositories': typeof SettingsRepositoriesRoute
  '/settings/runtimes': typeof SettingsRuntimesRoute
  '/issues': typeof IssuesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/runs/$runId/diff': typeof RunsRunIdDiffRoute
  '/runs/$runId': typeof RunsRunIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/runs/$runId': typeof RunsRunIdRouteRouteWithChildren
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/repositories': typeof SettingsRepositoriesRoute
  '/settings/runtimes': typeof SettingsRuntimesRoute
  '/issues/': typeof IssuesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/runs/$runId/diff': typeof RunsRunIdDiffRoute
  '/runs/$runId/': typeof RunsRunIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/runs/$runId'
    | '/issues/$issueId'
    | '/settings/about'
    | '/settings/agents'
    | '/settings/appearance'
    | '/settings/repositories'
    | '/settings/runtimes'
    | '/issues/'
    | '/settings/'
    | '/runs/$runId/diff'
    | '/runs/$runId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/issues/$issueId'
    | '/settings/about'
    | '/settings/agents'
    | '/settings/appearance'
    | '/settings/repositories'
    | '/settings/runtimes'
    | '/issues'
    | '/settings'
    | '/runs/$runId/diff'
    | '/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/runs/$runId'
    | '/issues/$issueId'
    | '/settings/about'
    | '/settings/agents'
    | '/settings/appearance'
    | '/settings/repositories'
    | '/settings/runtimes'
    | '/issues/'
    | '/settings/'
    | '/runs/$runId/diff'
    | '/runs/$runId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  RunsRunIdRouteRoute: typeof RunsRunIdRouteRouteWithChildren
  IssuesIssueIdRoute: typeof IssuesIssueIdRoute
  IssuesIndexRoute: typeof IssuesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/issues/': {
      id: '/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof IssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/runtimes': {
      id: '/settings/runtimes'
      path: '/runtimes'
      fullPath: '/settings/runtimes'
      preLoaderRoute: typeof SettingsRuntimesRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/repositories': {
      id: '/settings/repositories'
      path: '/repositories'
      fullPath: '/settings/repositories'
      preLoaderRoute: typeof SettingsRepositoriesRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/agents': {
      id: '/settings/agents'
      path: '/agents'
      fullPath: '/settings/agents'
      preLoaderRoute: typeof SettingsAgentsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/issues/$issueId': {
      id: '/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/issues/$issueId'
      preLoaderRoute: typeof IssuesIssueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId/': {
      id: '/runs/$runId/'
      path: '/'
      fullPath: '/runs/$runId/'
      preLoaderRoute: typeof RunsRunIdIndexRouteImport
      parentRoute: typeof RunsRunIdRouteRoute
    }
    '/runs/$runId/diff': {
      id: '/runs/$runId/diff'
      path: '/diff'
      fullPath: '/runs/$runId/diff'
      preLoaderRoute: typeof RunsRunIdDiffRouteImport
      parentRoute: typeof RunsRunIdRouteRoute
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsAgentsRoute: typeof SettingsAgentsRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsRepositoriesRoute: typeof SettingsRepositoriesRoute
  SettingsRuntimesRoute: typeof SettingsRuntimesRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAgentsRoute: SettingsAgentsRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsRepositoriesRoute: SettingsRepositoriesRoute,
  SettingsRuntimesRoute: SettingsRuntimesRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface RunsRunIdRouteRouteChildren {
  RunsRunIdDiffRoute: typeof RunsRunIdDiffRoute
  RunsRunIdIndexRoute: typeof RunsRunIdIndexRoute
}

const RunsRunIdRouteRouteChildren: RunsRunIdRouteRouteChildren = {
  RunsRunIdDiffRoute: RunsRunIdDiffRoute,
  RunsRunIdIndexRoute: RunsRunIdIndexRoute,
}

const RunsRunIdRouteRouteWithChildren = RunsRunIdRouteRoute._addFileChildren(
  RunsRunIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  RunsRunIdRouteRoute: RunsRunIdRouteRouteWithChildren,
  IssuesIssueIdRoute: IssuesIssueIdRoute,
  IssuesIndexRoute: IssuesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
