/**
 * Zod contracts shared by daemon and client: HTTP request/response shapes
 * (`api`), the canonical run diff with its pin-to-SHA anchors (`diff`), the
 * persisted entity mirrors (`entities`), and the Electron shell's renderer
 * bridge surface (`desktop`). Parsing a payload through the zod schemas is what
 * guarantees both sides agree on wire shape and invariants.
 *
 * @packageDocumentation
 */
export * from "./api.js";
export * from "./desktop.js";
export * from "./diff.js";
export {
  agentProfileContractSchema,
  agentSessionContractSchema,
  competeGroupContractSchema,
  ISSUE_EXECUTION_STATES,
  issueContractSchema,
  issueExecutionSchema,
  issueSourceContractSchema,
  projectIssueExecution,
  isRunPlanCompeteGroup,
  projectContractSchema,
  pullRequestContractSchema,
  repositoryContractSchema,
  resolvedAgentConfigSchema,
  resolvedSkillSchema,
  reviewCommentContractSchema,
  reviewContractSchema,
  runContractSchema,
  runPlanSchema,
  runPlanCompeteGroupSchema,
  runPlanCompetitorSchema,
  runPlanNodeSchema,
  runPlanStepSchema,
  skillContractSchema,
  skillInvalidReasonSchema,
  skillSourceSchema,
  skillStatusSchema,
  SKILL_INVALID_REASONS,
  SKILL_SOURCES,
  SKILL_STATUSES,
  sourceLabelSchema,
  stepRunContractSchema,
  WORKTREE_STATUSES,
  worktreeStatusSchema,
  type AgentProfileContract,
  type AgentSessionContract,
  type CompeteGroupContract,
  type ExternalIssueSource,
  type IssueContract,
  type IssueExecution,
  type IssueExecutionEvidence,
  type IssueExecutionState,
  type IssueSource,
  type IssueSourceContract,
  type ProjectContract,
  type PullRequestContract,
  type RepositoryContract,
  type ResolvedAgentConfig,
  type ResolvedSkill,
  type ReviewCommentContract,
  type ReviewContract,
  type RunContract,
  type RunPlan,
  type RunPlanCompeteGroup,
  type RunPlanCompetitor,
  type RunPlanNode,
  type RunPlanStep,
  type SkillContract,
  type SkillInvalidReason,
  type SkillSource,
  type SkillStatus,
  type SourceLabel,
  type StepRunContract,
  type WorktreeStatus,
} from "./entities/index.js";
